before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    dir: cmd

    ldflags:
      - '-X github.com/labi-le/control-panel/internal.Version={{ .Tag }}'
      - '-X github.com/labi-le/control-panel/internal.BuildTime={{ .Date }}'
      - '-X github.com/labi-le/control-panel/internal.CommitHash={{ .Commit }}'
      - '-extldflags "-static"'
    flags:
      - -v
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - id: "control-panel"
    file_name_template: "{{ .ConventionalFileName }}"
    description: "Control Panel"
    formats:
      - deb
    license: "GPLv3"
    maintainer: "github.com/labi-le/control-panel/graphs/contributors"
    section: "default"
    priority: "extra"
    dependencies:
      - "apt"
    contents:
      - src: "./frontend/"
        dst: "/opt/{{ .ProjectName }}/static/"
        type: dir
    scripts:
      postremove: scripts/postremove.sh
      postinstall: scripts/postinstall.sh