// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/dashboard": {
            "post": {
                "description": "Get system information and state",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "Dashboard info",
                "parameters": [
                    {
                        "description": "Dashboard info",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structures.DashboardParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Dashboard info",
                        "schema": {
                            "$ref": "#/definitions/structures.Dashboard"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structures.Response"
                        }
                    }
                }
            }
        },
        "/disk_partitions": {
            "post": {
                "description": "Get disk partitions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "Disk partitions",
                "responses": {
                    "200": {
                        "description": "Disk partitions",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/structures.PartitionStat"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structures.Response"
                        }
                    }
                }
            }
        },
        "/settings": {
            "put": {
                "description": "Update settings",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Update settings",
                "parameters": [
                    {
                        "description": "Settings",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal.PanelSettings"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Settings",
                        "schema": {
                            "$ref": "#/definitions/internal.PanelSettings"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structures.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structures.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Get settings",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Get settings",
                "responses": {
                    "200": {
                        "description": "Settings",
                        "schema": {
                            "$ref": "#/definitions/internal.PanelSettings"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structures.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal.PanelSettings": {
            "type": "object",
            "properties": {
                "addr": {
                    "type": "string"
                },
                "debug_level": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "port": {
                    "type": "string"
                }
            }
        },
        "structures.CPULoad": {
            "type": "object",
            "properties": {
                "load": {
                    "type": "number"
                }
            }
        },
        "structures.Dashboard": {
            "type": "object",
            "properties": {
                "cpu_load": {
                    "$ref": "#/definitions/structures.CPULoad"
                },
                "io": {
                    "$ref": "#/definitions/structures.UsageStat"
                },
                "mem": {
                    "$ref": "#/definitions/structures.Memory"
                }
            }
        },
        "structures.DashboardParams": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string"
                }
            }
        },
        "structures.Memory": {
            "type": "object",
            "properties": {
                "free": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "structures.PartitionStat": {
            "type": "object",
            "properties": {
                "device": {
                    "type": "string"
                },
                "fstype": {
                    "type": "string"
                },
                "mountpoint": {
                    "type": "string"
                },
                "opts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "structures.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "time": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "structures.UsageStat": {
            "type": "object",
            "properties": {
                "free": {
                    "type": "integer"
                },
                "fstype": {
                    "type": "string"
                },
                "inodesFree": {
                    "type": "integer"
                },
                "inodesTotal": {
                    "type": "integer"
                },
                "inodesUsed": {
                    "type": "integer"
                },
                "inodesUsedPercent": {
                    "type": "number"
                },
                "path": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                },
                "used": {
                    "type": "integer"
                },
                "usedPercent": {
                    "type": "number"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
